import argparse
import json
import os
import sys
import gc
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel


def resolve_base_model_name(model_path: str) -> str:
    adapter_config_path = os.path.join(model_path, "adapter_config.json")
    if os.path.exists(adapter_config_path):
        try:
            with open(adapter_config_path, "r", encoding="utf-8") as config_file:
                config = json.load(config_file)
            if config.get("base_model_name_or_path"):
                return str(config["base_model_name_or_path"])
        except Exception as exc:
            print(f"[parametric] Warning: failed reading adapter_config.json: {exc}", file=sys.stderr)
    # Fallback for older adapters / missing config metadata
    return "unsloth/qwen2.5-coder-3b-bnb-4bit"


def generate_openscad_code(model_path: str, prompt: str) -> str:
    """
    Load model, generate OpenSCAD code, unload model, return code.
    Models are loaded fresh on each request and released immediately after,
    so memory is only used when needed.
    """
    try:
        base_model_name = resolve_base_model_name(model_path)
        
        print(f"[parametric] Loading base model: {base_model_name}", file=sys.stderr)
        
        # Load tokenizer
        tokenizer = AutoTokenizer.from_pretrained(base_model_name)
        
        # Create offload directory for model layers that don't fit in memory
        offload_folder = os.path.join(os.path.dirname(model_path), "model_offload")
        os.makedirs(offload_folder, exist_ok=True)
        
        # Load base model with 4-bit quantization and offloading
        model = AutoModelForCausalLM.from_pretrained(
            base_model_name,
            device_map="auto",
            trust_remote_code=True,
            load_in_4bit=True,
            offload_folder=offload_folder,
            low_cpu_mem_usage=True,
        )
        
        # Load LoRA adapter
        print(f"[parametric] Loading LoRA adapter from: {model_path}", file=sys.stderr)
        model = PeftModel.from_pretrained(model, model_path)
        model.eval()
        
        print("[parametric] Model loaded successfully", file=sys.stderr)
        
        # Format the prompt for code generation
        formatted_prompt = f"Generate OpenSCAD code for: {prompt}\n\n// OpenSCAD code:\n"
        
        # Tokenize input
        inputs = tokenizer(formatted_prompt, return_tensors="pt").to(model.device)
        
        print(f"[parametric] Generating code for prompt: '{prompt}'", file=sys.stderr)
        
        # Generate with appropriate parameters for code generation
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=512,
                temperature=0.7,
                top_p=0.95,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id,
            )
        
        # Decode the generated code
        generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
        
        # Extract only the generated code (remove the prompt part)
        code = generated_text[len(formatted_prompt):].strip()
        
        return code
        
    finally:
        # --- unload models regardless of success/failure ---
        print("[parametric] Unloading models", file=sys.stderr)
        try:
            del model, tokenizer, inputs, outputs
        except:
            pass
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()
        print("[parametric] Models cleared", file=sys.stderr)


def main() -> int:
    parser = argparse.ArgumentParser(description="Local parametric model runner")
    parser.add_argument("--model", required=True, help="Path to the LoRA adapter model")
    parser.add_argument("--prompt", required=True, help="Parametric modeling prompt")
    args = parser.parse_args()

    model_path = os.path.abspath(args.model)

    if not os.path.exists(model_path):
        print(json.dumps({
            "error": f"Model path does not exist: {model_path}"
        }), file=sys.stderr)
        return 1

    try:
        # Generate code (model is loaded and unloaded inside this function)
        generated_code = generate_openscad_code(model_path, args.prompt)
        
        # Return formatted response
        response = {
            "code": generated_code,
            "message": "Generated by openscad_lora_model_3b",
        }
        
        print(json.dumps(response))
        return 0
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        print(json.dumps({
            "error": f"Generation failed: {str(e)}"
        }), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
