import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SHAPE_E_BASE_URL = (process.env.SHAPE_E_BASE_URL || "http://127.0.0.1:5010").replace(/\/$/, "");
const PARAMETRIC_MODEL_URL = process.env.PARAMETRIC_MODEL_URL?.replace(/\/$/, "");

type ParametricResult = {
  code: string;
  message: string;
};

function classifyPrompt(prompt: string): "organic" | "parametric" {
  const organicKeywords = [
    "animal",
    "creature",
    "human",
    "face",
    "body",
    "tree",
    "flower",
    "plant",
    "organic",
    "character",
    "shark",
    "fish",
    "dragon",
    "sculpture",
    "blob",
  ];

  const normalizedPrompt = prompt.toLowerCase();
  return organicKeywords.some((keyword) => normalizedPrompt.includes(keyword))
    ? "organic"
    : "parametric";
}

async function generateParametricModel(prompt: string): Promise<ParametricResult> {
  // This is the extension point for your future fine-tuned parametric model.
  // If you expose it as an HTTP service, set PARAMETRIC_MODEL_URL and return
  // JSON shaped like: { code: string, message?: string }.
  if (!PARAMETRIC_MODEL_URL) {
    throw Object.assign(
      new Error("Parametric model is not configured yet. Set PARAMETRIC_MODEL_URL or replace generateParametricModel()."),
      { statusCode: 501 },
    );
  }

  const response = await fetch(PARAMETRIC_MODEL_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw Object.assign(
      new Error(`Parametric model request failed (${response.status}): ${errorText || "Unknown error"}`),
      { statusCode: response.status },
    );
  }

  const result = (await response.json()) as Partial<ParametricResult>;
  if (!result.code) {
    throw Object.assign(
      new Error("Parametric model response must include a 'code' field."),
      { statusCode: 502 },
    );
  }

  return {
    code: result.code,
    message: result.message || "Generated by custom parametric model",
  };
}

async function generateOrganicModel(prompt: string) {
  const response = await fetch(`${SHAPE_E_BASE_URL}/shap-e`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ text: prompt }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw Object.assign(
      new Error(`Shape-E service request failed (${response.status}): ${errorText || "Unknown error"}`),
      { statusCode: response.status },
    );
  }

  const result = (await response.json()) as {
    files?: string[];
    download_urls?: string[];
  };

  const objFile = result.files?.find((file) => file.toLowerCase().endsWith(".obj")) || null;
  const plyFile = result.files?.find((file) => file.toLowerCase().endsWith(".ply")) || null;

  return {
    files: result.files || [],
    objFile,
    plyFile,
    objUrl: objFile ? `/api/organic/download/${encodeURIComponent(objFile)}` : null,
    plyUrl: plyFile ? `/api/organic/download/${encodeURIComponent(plyFile)}` : null,
    message: "Generated by local Shape-E service",
  };
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Routes
  app.post("/api/route", async (req, res) => {
    const { prompt } = req.body;
    if (!prompt) return res.status(400).json({ error: "Prompt is required" });

    try {
      const route = classifyPrompt(prompt);
      
      if (route === "parametric") {
        const parametricResponse = await generateParametricModel(prompt);
        return res.json({
          type: "parametric",
          code: parametricResponse.code,
          message: parametricResponse.message,
        });
      }

      const organicResponse = await generateOrganicModel(prompt);
      return res.json({
        type: "organic",
        data: organicResponse,
        message: organicResponse.message,
      });
    } catch (error) {
      console.error("Pipeline error:", error);
      const statusCode =
        typeof error === "object" && error && "statusCode" in error && typeof error.statusCode === "number"
          ? error.statusCode
          : 500;
      const message = error instanceof Error ? error.message : "Failed to process request";
      res.status(statusCode).json({ error: message });
    }
  });

  app.get("/api/organic/download/:filename", async (req, res) => {
    try {
      const response = await fetch(`${SHAPE_E_BASE_URL}/shap-e/download/${encodeURIComponent(req.params.filename)}`);
      if (!response.ok) {
        const errorText = await response.text();
        return res.status(response.status).json({
          error: errorText || `Failed to download ${req.params.filename} from Shape-E service`,
        });
      }

      const contentType = response.headers.get("content-type");
      if (contentType) {
        res.setHeader("Content-Type", contentType);
      }
      const contentDisposition = response.headers.get("content-disposition");
      if (contentDisposition) {
        res.setHeader("Content-Disposition", contentDisposition);
      }
      const fileBuffer = Buffer.from(await response.arrayBuffer());
      res.send(fileBuffer);
    } catch (error) {
      console.error("Organic download proxy error:", error);
      res.status(500).json({ error: "Failed to proxy organic asset" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
