import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { spawn } from "child_process";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PARAMETRIC_MODEL_URL = process.env.PARAMETRIC_MODEL_URL?.replace(/\/$/, "");
const PARAMETRIC_MODEL_PATH = process.env.PARAMETRIC_MODEL_PATH;
const PARAMETRIC_RUNNER_SCRIPT = process.env.PARAMETRIC_RUNNER_SCRIPT || path.join(__dirname, "parametric_runner.py");
const SHAPE_E_RUNNER_SCRIPT = process.env.SHAPE_E_RUNNER_SCRIPT || path.join(__dirname, "shape_e_runner.py");
const SHAPE_E_OUTPUT_DIR = process.env.SHAPE_E_OUTPUT_DIR || path.join(__dirname, "shap_e_outputs");
const PYTHON_EXECUTABLE = process.env.PARAMETRIC_PYTHON_BIN || "python";

type ParametricResult = {
  code: string;
  message: string;
};

type OrganicResult = {
  files: string[];
  message: string;
};

function classifyPrompt(prompt: string): "organic" | "parametric" {
  const organicKeywords = [
    "animal",
    "creature",
    "human",
    "face",
    "body",
    "tree",
    "flower",
    "plant",
    "organic",
    "character",
    "shark",
    "fish",
    "dragon",
    "sculpture",
    "blob",
  ];

  const normalizedPrompt = prompt.toLowerCase();
  return organicKeywords.some((keyword) => normalizedPrompt.includes(keyword))
    ? "organic"
    : "parametric";
}

async function generateParametricModel(prompt: string): Promise<ParametricResult> {
  if (PARAMETRIC_MODEL_PATH) {
    return runLocalParametricModel(prompt);
  }

  // This is the extension point for your future fine-tuned parametric model.
  // If you expose it as an HTTP service, set PARAMETRIC_MODEL_URL and return
  // JSON shaped like: { code: string, message?: string }.
  if (!PARAMETRIC_MODEL_URL) {
    throw Object.assign(
      new Error("Parametric model is not configured yet. Set PARAMETRIC_MODEL_URL or replace generateParametricModel()."),
      { statusCode: 501 },
    );
  }

  const response = await fetch(PARAMETRIC_MODEL_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw Object.assign(
      new Error(`Parametric model request failed (${response.status}): ${errorText || "Unknown error"}`),
      { statusCode: response.status },
    );
  }

  const result = (await response.json()) as Partial<ParametricResult>;
  if (!result.code) {
    throw Object.assign(
      new Error("Parametric model response must include a 'code' field."),
      { statusCode: 502 },
    );
  }

  return {
    code: result.code,
    message: result.message || "Generated by custom parametric model",
  };
}

async function runLocalParametricModel(prompt: string): Promise<ParametricResult> {
  return new Promise((resolve, reject) => {
    const child = spawn(
      PYTHON_EXECUTABLE,
      [PARAMETRIC_RUNNER_SCRIPT, "--model", PARAMETRIC_MODEL_PATH!, "--prompt", prompt],
      {
        cwd: __dirname,
        env: process.env,
        stdio: ["ignore", "pipe", "pipe"],
      },
    );

    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString();
    });

    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });

    child.on("error", (error) => {
      reject(
        Object.assign(
          new Error(`Failed to start local parametric runner: ${error.message}`),
          { statusCode: 500 },
        ),
      );
    });

    child.on("close", (code) => {
      if (code !== 0) {
        reject(
          Object.assign(
            new Error(stderr.trim() || `Local parametric runner exited with code ${code}`),
            { statusCode: 500 },
          ),
        );
        return;
      }

      try {
        const parsed = JSON.parse(stdout) as Partial<ParametricResult>;
        if (!parsed.code) {
          reject(
            Object.assign(
              new Error("Local parametric runner must return JSON with a 'code' field."),
              { statusCode: 502 },
            ),
          );
          return;
        }

        resolve({
          code: parsed.code,
          message: parsed.message || "Generated by local parametric model",
        });
      } catch (error) {
        reject(
          Object.assign(
            new Error(`Invalid JSON from local parametric runner: ${stdout || String(error)}`),
            { statusCode: 502 },
          ),
        );
      }
    });
  });
}

async function runLocalShapeERunner(prompt: string): Promise<OrganicResult> {
  return new Promise((resolve, reject) => {
    const child = spawn(
      PYTHON_EXECUTABLE,
      [SHAPE_E_RUNNER_SCRIPT, "--prompt", prompt, "--output-dir", SHAPE_E_OUTPUT_DIR],
      {
        cwd: __dirname,
        env: process.env,
        stdio: ["ignore", "pipe", "pipe"],
      },
    );

    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString();
    });

    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
      // Print Shape-E progress to console
      process.stderr.write(chunk);
    });

    child.on("error", (error) => {
      reject(
        Object.assign(
          new Error(`Failed to start Shape-E runner: ${error.message}`),
          { statusCode: 500 },
        ),
      );
    });

    child.on("close", (code) => {
      if (code !== 0) {
        reject(
          Object.assign(
            new Error(stderr.trim() || `Shape-E runner exited with code ${code}`),
            { statusCode: 500 },
          ),
        );
        return;
      }

      try {
        const parsed = JSON.parse(stdout) as Partial<OrganicResult>;
        if (!parsed.files) {
          reject(
            Object.assign(
              new Error("Shape-E runner must return JSON with a 'files' field."),
              { statusCode: 502 },
            ),
          );
          return;
        }

        resolve({
          files: parsed.files,
          message: parsed.message || "Generated by Shape-E",
        });
      } catch (error) {
        reject(
          Object.assign(
            new Error(`Invalid JSON from Shape-E runner: ${stdout || String(error)}`),
            { statusCode: 502 },
          ),
        );
      }
    });
  });
}

async function generateOrganicModel(prompt: string) {
  const result = await runLocalShapeERunner(prompt);

  const objFile = result.files.find((file) => file.toLowerCase().endsWith(".obj")) || null;
  const plyFile = result.files.find((file) => file.toLowerCase().endsWith(".ply")) || null;

  return {
    files: result.files,
    objFile,
    plyFile,
    objUrl: objFile ? `/api/organic/download/${encodeURIComponent(objFile)}` : null,
    plyUrl: plyFile ? `/api/organic/download/${encodeURIComponent(plyFile)}` : null,
    message: result.message,
  };
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Routes
  app.post("/api/route", async (req, res) => {
    const { prompt } = req.body;
    if (!prompt) return res.status(400).json({ error: "Prompt is required" });

    try {
      const route = classifyPrompt(prompt);
      
      if (route === "parametric") {
        const parametricResponse = await generateParametricModel(prompt);
        return res.json({
          type: "parametric",
          code: parametricResponse.code,
          message: parametricResponse.message,
        });
      }

      const organicResponse = await generateOrganicModel(prompt);
      return res.json({
        type: "organic",
        data: organicResponse,
        message: organicResponse.message,
      });
    } catch (error) {
      console.error("Pipeline error:", error);
      const statusCode =
        typeof error === "object" && error && "statusCode" in error && typeof error.statusCode === "number"
          ? error.statusCode
          : 500;
      const message = error instanceof Error ? error.message : "Failed to process request";
      res.status(statusCode).json({ error: message });
    }
  });

  app.get("/api/organic/download/:filename", (req, res) => {
    try {
      const filename = req.params.filename;
      const filePath = path.join(SHAPE_E_OUTPUT_DIR, filename);
      
      // Security check: ensure the file is within the output directory
      const normalizedPath = path.normalize(filePath);
      if (!normalizedPath.startsWith(path.normalize(SHAPE_E_OUTPUT_DIR))) {
        return res.status(403).json({ error: "Access denied" });
      }

      res.download(filePath, filename, (err) => {
        if (err) {
          console.error("File download error:", err);
          if (!res.headersSent) {
            res.status(404).json({ error: `File not found: ${filename}` });
          }
        }
      });
    } catch (error) {
      console.error("Organic download error:", error);
      res.status(500).json({ error: "Failed to download file" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
