"""
Shape-E runner script for on-demand 3D mesh generation.
Models are loaded fresh on each request and released immediately after,
so memory is only used when needed.
"""

import argparse
import gc
import json
import os
import sys
import torch


def run_shap_e(text: str, output_dir: str, batch_size: int = 1):
    """
    Load models, generate meshes, unload models, return file paths.
    Everything is imported *inside* this function so that no shap-e /
    torch state leaks into module-level memory between calls.
    """
    # --- lazy imports so nothing loads at startup ---
    from shap_e.diffusion.gaussian_diffusion import diffusion_from_config
    from shap_e.diffusion.sample import sample_latents
    from shap_e.models.download import load_config, load_model
    from shap_e.util.notebooks import decode_latent_mesh

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # --- load models ---
    print(f"[shap-e] Loading models on {device}", file=sys.stderr)
    xm = load_model("transmitter", device=device)
    model = load_model("text300M", device=device)
    diffusion = diffusion_from_config(load_config("diffusion"))

    try:
        # --- sample latents ---
        print(f"[shap-e] Sampling for prompt: '{text}'", file=sys.stderr)
        latents = sample_latents(
            batch_size=batch_size,
            model=model,
            diffusion=diffusion,
            guidance_scale=15.0,
            model_kwargs=dict(texts=[text] * batch_size),
            progress=True,
            clip_denoised=True,
            use_fp16=True,
            use_karras=True,
            karras_steps=16,
            sigma_min=1e-3,
            sigma_max=160,
            s_churn=0,
        )

        # --- decode & save meshes ---
        saved_files = []
        for i, latent in enumerate(latents):
            tri = decode_latent_mesh(xm, latent).tri_mesh()

            ply_name = f"mesh_{i}.ply"
            obj_name = f"mesh_{i}.obj"

            ply_path = os.path.join(output_dir, ply_name)
            obj_path = os.path.join(output_dir, obj_name)

            with open(ply_path, "wb") as f:
                tri.write_ply(f)
            with open(obj_path, "w") as f:
                tri.write_obj(f)

            saved_files.append(ply_name)
            saved_files.append(obj_name)
            print(f"[shap-e] Saved {ply_name} and {obj_name}", file=sys.stderr)

        return saved_files

    finally:
        # --- unload models regardless of success/failure ---
        print("[shap-e] Unloading models", file=sys.stderr)
        try:
            del model, xm, diffusion, latents
        except:
            pass
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()
        print("[shap-e] Models cleared", file=sys.stderr)


def main() -> int:
    parser = argparse.ArgumentParser(description="Shape-E runner for on-demand mesh generation")
    parser.add_argument("--prompt", required=True, help="Text prompt for 3D mesh generation")
    parser.add_argument("--output-dir", required=True, help="Directory to save generated files")
    args = parser.parse_args()

    # Create output directory if it doesn't exist
    os.makedirs(args.output_dir, exist_ok=True)

    try:
        # Generate meshes
        files = run_shap_e(args.prompt, args.output_dir)
        
        # Return formatted response
        response = {
            "files": files,
            "message": "Generated by Shape-E",
        }
        
        print(json.dumps(response))
        return 0
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        print(json.dumps({
            "error": f"Generation failed: {str(e)}"
        }), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
